const SERIES={
'squish-man':{name:'The Amazing Adventures of Squish Man',env:'SAMPLE_URL_SQUISH_MAN'},
'messiah':{name:'Messiah Adventures',env:'SAMPLE_URL_MESSIAH'},
'ruben':{name:'Ruben Adventures',env:'SAMPLE_URL_RUBEN'},
'champagne-hearts':{name:'Champagne Hearts',env:'SAMPLE_URL_CHAMPAGNE_HEARTS'},
'uptown-testimony':{name:'Uptown Testimony',env:'SAMPLE_URL_UPTOWN_TESTIMONY'},
'rizzmeister':{name:'Rizzmeister',env:'SAMPLE_URL_RIZZMEISTER'}};
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=UTF-8','cache-control':'no-store'}})}
export async function onRequestPost(context){try{const body=await context.request.json();if(body.website)return json({ok:true});const firstName=String(body.firstName||'').trim().slice(0,80),email=String(body.email||'').trim().toLowerCase().slice(0,254),seriesKey=String(body.series||'').trim();if(!firstName||!/^\S+@\S+\.\S+$/.test(email)||body.adultConfirmed!==true)return json({ok:false,message:'Please complete the required fields and confirm you are an adult.'},400);const series=SERIES[seriesKey];if(!series)return json({ok:false,message:'Please choose an available series.'},400);const sampleUrl=context.env[series.env];if(!sampleUrl)return json({ok:false,message:'That series sample is not available yet. Please choose another series.'},409);if(!context.env.RESEND_API_KEY)return json({ok:false,message:'Sample delivery is temporarily unavailable. Please try again later.'},503);const r=await fetch('https://api.resend.com/events',{method:'POST',headers:{Authorization:`Bearer ${context.env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({event:'sample.requested',email,payload:{series_name:series.name,sample_url:sampleUrl}})});if(!r.ok)return json({ok:false,message:'We could not send your sample right now. Please try again shortly.'},502);return json({ok:true,message:`Your ${series.name} sample is on its way. Check your email.`});}catch(_){return json({ok:false,message:'We could not process your request. Please try again.'},500)}}
export async function onRequest(context){if(context.request.method!=='POST')return json({ok:false,message:'Method not allowed.'},405);return onRequestPost(context)}
